name: Docker Image CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Publish to Docker Hub
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: arakattack/laravel-deployer
        tags: ${{ github.run_number }}
